apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster1
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyName: aws
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 1
    ssh:    
      publicKeyName: aws
